### ISSUE TITLE
[教程]快速适配新页面

### ISSUE THREAD

**Issue by TC999** [BewlyBewly/BewlyBewly#902]
# 快速适配新页面
> [!CAUTION]
> **注**：本教程仅作为参考，如有问题请在本议题（issue）下评论指出

## 开始
1. 按照插件贡献文档配置：([English](https://github.com/BewlyBewly/BewlyBewly/blob/main/docs/CONTRIBUTING.md) | [简体中文](https://github.com/BewlyBewly/BewlyBewly/blob/main/docs/CONTRIBUTING-cmn_CN.md) | [正體中文](https://github.com/BewlyBewly/BewlyBewly/blob/main/docs/CONTRIBUTING-cmn_TW.md) | [粵語](https://github.com/BewlyBewly/BewlyBewly/blob/main/docs/CONTRIBUTING-jyut.md))
2. 找到你需要适配的网址，这里用 <https://passport.bilibili.com/login>（登录页）举例。
3. 打开`manifest.ts`，找到`content_scripts`项，在`matches`中查看是否有匹配，如果没有就添加，注意将开头的`http`或`https`以及二级域名替换为`*`，例如上方网址变为：
```ts
'*://passport.bilibili.com/*',
```
4. 打开`src\contentScripts\index.ts`，找到`function isSupportedPages()`项，在函数底部添加网址正则表达式，记得添加注释，例如
```ts
// 登录页
|| /^https?:\/\/passport\.bilibili\.com\/login.*$/.test(currentUrl)
```
5. 打开`src\styles\adaptedStyles`，创建新文件名为`pageName.scss`，在`index.ts`中找到`async function setupStyles()`函数添加网址正则表达式，同时链接刚新建的`.scss`文件，示例代码
``` index.ts
// 登录页
  else if (/https?:\/\/passport\.bilibili\.com\/login*/.test(currentUrl)) { // 网址正则表达式
    await import('./loginPage.scss') //这里放刚新建的文件名
    document.documentElement.classList.add('loginPage')  // 同上，注意删除后缀
  }
```
6. 编写css样式，编写规范：([English](https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/adaptedStyles/adaptedStyles.md) | [简体中文](https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/adaptedStyles/adaptedStyles-cmn_CN.md) | [正體中文](https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/adaptedStyles/adaptedStyles-cmn_TW.md) | [粵語](https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/adaptedStyles/adaptedStyles-jyut.md))，颜色参照[variables.scss](https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/variables.scss)
补充：
``` scss
.bewly-design.loginPage {
  // 固定修改区域，比如隐藏，写死颜色等
 .top-header {
   display: none;
 }
 ……
 // #region 主题颜色适配部分（调色板）
  :not(foobar) {
    a,
    b,
    c {
       color: var(--bew-theme-color);
      }
  ……
  }
  // #endregion 
  // #region 深色模式特有修改
  &.dark {
    d,
    e,
    f {
      background: var(--bew-bg);
    }
    g,
    h,
    i {
      color: var(--bew-text-1);
    }
  }
// #endregion
}
```
7. 按照贡献文档调试
8. 效果示例：
    - 浅色模式：
    ![image](https://github.com/user-attachments/assets/9dd66167-0245-48de-905a-3ad4acbce7bf)

    - 深色模式
    ![image](https://github.com/user-attachments/assets/9b1b52a0-f710-4003-80cc-430346a7e9a2)
9. 附自己编译的[测试版](https://github.com/TC999/BewlyBewly/releases/tag/v0.25-beta1)，可安装体验
